<?php

use CodeIgniter\Router\RouteCollection;

/** @var RouteCollection $routes */

// -----------------------------------------------------------------------
// Service Desk web (protected + module access)
// Used by the ServiceDesk role (and SuperAdmin) to run bulk imports.
// -----------------------------------------------------------------------
$routes->group('servicedesk', [
    'namespace' => 'App\Modules\ServiceDesk\Controllers',
    'filter'    => ['auth', 'module_access:servicedesk'],
], function (RouteCollection $routes): void {

    // Dashboard
    $routes->get('/', 'ServiceDesk::index', ['as' => 'servicedesk.index']);

    // Template download (autogenerated from the live GLPI plugin schema)
    $routes->get('template', 'ServiceDesk::downloadTemplate', ['as' => 'servicedesk.template']);

    // Bulk import: upload + validate + enqueue
    $routes->post('imports', 'ServiceDesk::upload', ['as' => 'servicedesk.imports.upload']);

    // Import history + monitoring
    $routes->get('imports',                'ServiceDesk::imports',        ['as' => 'servicedesk.imports.index']);
    $routes->get('imports/(:num)',         'ServiceDesk::show/$1',        ['as' => 'servicedesk.imports.show']);
    $routes->get('imports/(:num)/status',  'ServiceDesk::status/$1',      ['as' => 'servicedesk.imports.status']);
    $routes->get('imports/(:num)/log',     'ServiceDesk::log/$1',         ['as' => 'servicedesk.imports.log']);
    $routes->get('imports/(:num)/output',  'ServiceDesk::downloadOutput/$1', ['as' => 'servicedesk.imports.output']);
});

// -----------------------------------------------------------------------
// Service Desk administration — SuperAdmin only, under /admin
// The admin sets the import ceilings and GLPI targets the operators consume.
// -----------------------------------------------------------------------
$routes->group('admin/servicedesk', [
    'namespace' => 'App\Modules\ServiceDesk\Controllers',
    'filter'    => ['auth', 'super_admin'],
], function (RouteCollection $routes): void {
    $routes->get('settings',       'ServiceDeskAdmin::settings',     ['as' => 'servicedesk.settings']);
    $routes->post('settings',      'ServiceDeskAdmin::saveSettings', ['as' => 'servicedesk.settings.save']);
    // Category -> CLIENTE mapping + supported categories for the template.
    $routes->get('categories',     'ServiceDeskAdmin::categories',     ['as' => 'servicedesk.categories']);
    $routes->post('categories',    'ServiceDeskAdmin::saveCategories', ['as' => 'servicedesk.categories.save']);
    // Live preview of the introspected plugin containers/fields.
    $routes->get('schema',         'ServiceDeskAdmin::schema',       ['as' => 'servicedesk.schema']);
});

// -----------------------------------------------------------------------
// API v1 Service Desk (protected + module access)
// -----------------------------------------------------------------------
$routes->group('api/v1/servicedesk', [
    'namespace' => 'App\Modules\ServiceDesk\Controllers\Api',
    'filter'    => ['api_auth', 'module_access:servicedesk'],
], function (RouteCollection $routes): void {
    $routes->get('template',        'ServiceDeskApiController::template');
    $routes->get('schema',          'ServiceDeskApiController::schema');
    $routes->get('imports',         'ServiceDeskApiController::listImports');
    $routes->post('imports',        'ServiceDeskApiController::createImport');
    $routes->get('imports/(:num)',  'ServiceDeskApiController::showImport/$1');
});
