<?php

use CodeIgniter\Router\RouteCollection;

/** @var RouteCollection $routes */

// -----------------------------------------------------------------------
// Service Desk web (protected + module access)
// Used by the ServiceDesk role (and SuperAdmin) to run bulk imports.
// -----------------------------------------------------------------------
$routes->group('servicedesk', [
    'namespace' => 'App\Modules\ServiceDesk\Controllers',
    'filter'    => ['auth', 'module_access:servicedesk'],
], function (RouteCollection $routes): void {

    // Dashboard
    $routes->get('/', 'ServiceDesk::index', ['as' => 'servicedesk.index']);

    // AI ticket creator: chat -> editable proposal -> enqueue into the pipeline
    $routes->get('creator',          'TicketCreator::index',  ['as' => 'servicedesk.creator']);
    $routes->post('creator/columns', 'TicketCreator::columns', ['as' => 'servicedesk.creator.columns']);
    $routes->post('creator/chat',    'TicketCreator::chat',   ['as' => 'servicedesk.creator.chat']);
    $routes->post('creator/tickets', 'TicketCreator::create', ['as' => 'servicedesk.creator.create']);
    $routes->post('creator/reset',   'TicketCreator::reset',  ['as' => 'servicedesk.creator.reset']);

    // Agent self-view: my audited deviations (confirmed) + escalations
    $routes->get('mi-desempeno', 'MyPerformance::index', ['as' => 'servicedesk.myperformance']);

    // Template download (autogenerated from the live GLPI plugin schema)
    $routes->get('template', 'ServiceDesk::downloadTemplate', ['as' => 'servicedesk.template']);

    // Bulk import: upload + validate + enqueue
    $routes->post('imports', 'ServiceDesk::upload', ['as' => 'servicedesk.imports.upload']);

    // Bulk update + close: same Excel, but TICKET_ID filled in by the operator.
    $routes->get('actualizar',  'ServiceDesk::updateForm',   ['as' => 'servicedesk.update']);
    $routes->post('actualizar', 'ServiceDesk::uploadUpdate', ['as' => 'servicedesk.update.upload']);

    // Import history + monitoring
    $routes->get('imports',                'ServiceDesk::imports',        ['as' => 'servicedesk.imports.index']);
    $routes->get('imports/(:num)',         'ServiceDesk::show/$1',        ['as' => 'servicedesk.imports.show']);
    $routes->get('imports/(:num)/status',  'ServiceDesk::status/$1',      ['as' => 'servicedesk.imports.status']);
    $routes->get('imports/(:num)/log',     'ServiceDesk::log/$1',         ['as' => 'servicedesk.imports.log']);
    $routes->get('imports/(:num)/output',  'ServiceDesk::downloadOutput/$1', ['as' => 'servicedesk.imports.output']);
    // Aplicar de verdad una simulación terminada, reusando su mismo archivo.
    $routes->post('imports/(:num)/aplicar', 'ServiceDesk::applySimulation/$1', ['as' => 'servicedesk.imports.apply']);
});

// -----------------------------------------------------------------------
// Service Desk administration — SuperAdmin only, under /admin
// The admin sets the import ceilings and GLPI targets the operators consume.
// -----------------------------------------------------------------------
$routes->group('admin/servicedesk', [
    'namespace' => 'App\Modules\ServiceDesk\Controllers',
    'filter'    => ['auth', 'super_admin'],
], function (RouteCollection $routes): void {
    $routes->get('settings',       'ServiceDeskAdmin::settings',     ['as' => 'servicedesk.settings']);
    $routes->post('settings',      'ServiceDeskAdmin::saveSettings', ['as' => 'servicedesk.settings.save']);
    // AI creator config (Claude API key, model, budget) + usage log.
    $routes->post('ai',            'ServiceDeskAdmin::saveAi',        ['as' => 'servicedesk.ai.save']);
    // Self-service widget config (embed, origins, hardware mapping, limits).
    $routes->post('widget',        'ServiceDeskAdmin::saveWidget',    ['as' => 'servicedesk.widget.save']);
    // Bulk update + close: enable, reopen/verify toggles, default solution text.
    $routes->post('update',        'ServiceDeskAdmin::saveUpdate',    ['as' => 'servicedesk.update.save']);
    // Category -> CLIENTE mapping + supported categories for the template.
    $routes->get('categories',     'ServiceDeskAdmin::categories',     ['as' => 'servicedesk.categories']);
    $routes->post('categories',    'ServiceDeskAdmin::saveCategories', ['as' => 'servicedesk.categories.save']);
    // Daily backlog report: config, root category -> area mapping, and test send.
    $routes->post('backlog',       'ServiceDeskAdmin::saveBacklog',      ['as' => 'servicedesk.backlog.save']);
    $routes->post('backlog/areas', 'ServiceDeskAdmin::saveBacklogAreas', ['as' => 'servicedesk.backlog.areas.save']);
    $routes->post('backlog/test',  'ServiceDeskAdmin::sendBacklogTest',  ['as' => 'servicedesk.backlog.test']);
    // Live preview of the introspected plugin containers/fields.
    $routes->get('schema',         'ServiceDeskAdmin::schema',       ['as' => 'servicedesk.schema']);
    // Public self-service landing config (enable, title/intro, key, rate limit).
    $routes->post('landing',       'ServiceDeskAdmin::saveLanding',   ['as' => 'servicedesk.landing.save']);
});

// -----------------------------------------------------------------------
// Self-service widget — PUBLIC (no auth). Gated by widget_access:
// site key + origin allowlist + per-IP rate limit. Embeddable in the intranet.
// -----------------------------------------------------------------------
$routes->group('servicedesk/widget', [
    'namespace' => 'App\Modules\ServiceDesk\Controllers',
    'filter'    => 'widget_access',
], function (RouteCollection $routes): void {
    $routes->get('embed.js', 'Widget::embed',  ['as' => 'servicedesk.widget.embed']);
    $routes->get('frame',    'Widget::frame',   ['as' => 'servicedesk.widget.frame']);
    $routes->post('chat',    'Widget::chat',    ['as' => 'servicedesk.widget.chat']);
    $routes->post('ticket',  'Widget::ticket',  ['as' => 'servicedesk.widget.ticket']);
    $routes->options('(:any)', 'Widget::frame'); // CORS preflight (short-circuited by the filter)
});

// -----------------------------------------------------------------------
// Public self-service LANDING — PUBLIC (no auth), the ONLY public page.
// Standalone chat + form on Nexus's own domain; the user fills their identity
// and picks the ITIL category. Gated by landing_access: enabled + site key +
// same-origin + per-IP rate limit. Independent from the embeddable widget.
// -----------------------------------------------------------------------
$routes->group('soporte', [
    'namespace' => 'App\Modules\ServiceDesk\Controllers',
    'filter'    => 'landing_access',
], function (RouteCollection $routes): void {
    $routes->get('/',       'Landing::index',  ['as' => 'servicedesk.landing']);
    $routes->post('submit', 'Landing::submit', ['as' => 'servicedesk.landing.submit']); // complete manual form
    $routes->post('chat',   'Landing::chat',   ['as' => 'servicedesk.landing.chat']);   // floating chat
    $routes->post('ticket', 'Landing::ticket', ['as' => 'servicedesk.landing.ticket']); // floating chat -> create
    $routes->options('(:any)', 'Landing::index'); // CORS preflight (short-circuited by the filter)
});

// -----------------------------------------------------------------------
// API v1 Service Desk (protected + module access)
// -----------------------------------------------------------------------
$routes->group('api/v1/servicedesk', [
    'namespace' => 'App\Modules\ServiceDesk\Controllers\Api',
    'filter'    => ['api_auth', 'module_access:servicedesk'],
], function (RouteCollection $routes): void {
    $routes->get('template',        'ServiceDeskApiController::template');
    $routes->get('schema',          'ServiceDeskApiController::schema');
    $routes->get('imports',         'ServiceDeskApiController::listImports');
    $routes->post('imports',        'ServiceDeskApiController::createImport');
    $routes->get('imports/(:num)',  'ServiceDeskApiController::showImport/$1');

    // Bulk update + close (mirror of the web actions). Same job table, mode=update.
    $routes->get('updates',         'ServiceDeskApiController::listUpdates');
    $routes->post('updates',        'ServiceDeskApiController::createUpdate');
    $routes->get('updates/(:num)',  'ServiceDeskApiController::showImport/$1');
    $routes->post('updates/(:num)/apply', 'ServiceDeskApiController::applyUpdate/$1');

    // Daily backlog report (mirror of the web action): preview data + trigger send.
    $routes->get('backlog/preview', 'ServiceDeskApiController::backlogPreview');
    $routes->post('backlog/send',   'ServiceDeskApiController::backlogSend');

    // AI ticket creator (mirror of the web actions; stateless conversation).
    $routes->post('creator/columns', 'TicketCreatorApiController::columns');
    $routes->post('creator/chat',    'TicketCreatorApiController::chat');
    $routes->post('creator/tickets', 'TicketCreatorApiController::create');
});
